- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: /home/swami/Desktop/maven56/target/maven56.war
        dest: /opt/tomcat/webapps/
        remote_src: yes

    
